import 'package:flutter/material.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget2/generated/GeneratedFrame3Widget6.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget2/generated/GeneratedRectangle40Widget.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget2/generated/GeneratedRectangle38Widget2.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget2/generated/GeneratedAddWidget2.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget2/generated/GeneratedRectangle39Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget2/generated/GeneratedDendronWidget7.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget2/generated/GeneratedFrame3Widget5.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget2/generated/GeneratedFrame27Widget1.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget2/generated/GeneratedRectangle39Widget.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget2/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget2/generated/GeneratedVectorWidget43.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget2/generated/GeneratedRectangle37Widget2.dart';

/* Frame 2nd page 
    Autogenerated by FlutLab FTF Generator
  */
class Generated2ndpageWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 175, 56),
                ),
              ),
              Positioned(
                left: 123.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 49.0,
                child: GeneratedDendronWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.0799218241373698;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      29.970684051513672;

                  double percentHeight = 0.044977740011830025;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      30.000152587890625;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.872,
                        translateY: constraints.maxHeight * 0.02848575712143928,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget43())
                  ]);
                }),
              ),
              Positioned(
                left: 36.0,
                top: 71.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 46.0,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 338.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 48.0,
                child: GeneratedFrame3Widget5(),
              ),
              Positioned(
                left: 303.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 50.0,
                child: GeneratedRectangle37Widget2(),
              ),
              Positioned(
                left: 36.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 48.0,
                child: GeneratedFrame3Widget6(),
              ),
              Positioned(
                left: 36.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 172.0,
                child: GeneratedFrame27Widget1(),
              ),
              Positioned(
                left: 36.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 410.0,
                child: GeneratedRectangle38Widget2(),
              ),
              Positioned(
                left: 311.0,
                top: 151.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 373.0,
                child: GeneratedRectangle39Widget(),
              ),
              Positioned(
                left: 306.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 50.0,
                child: GeneratedRectangle40Widget(),
              ),
              Positioned(
                left: 122.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 53.0,
                child: GeneratedRectangle39Widget1(),
              ),
              Positioned(
                left: 152.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 138.5078582763672,
                height: 51.489410400390625,
                child: GeneratedAddWidget2(),
              )
            ]),
      ),
    ));
  }
}
