import 'package:flutter/material.dart';
import 'package:flutterapp/dendronapp/generatedaccountwidget/generated/GeneratedSubmitWidget.dart';
import 'package:flutterapp/dendronapp/generatedaccountwidget/generated/GeneratedCodiconaccountWidget.dart';
import 'package:flutterapp/dendronapp/generatedaccountwidget/generated/GeneratedLastnameWidget.dart';
import 'package:flutterapp/dendronapp/generatedaccountwidget/generated/GeneratedRectangle9Widget5.dart';
import 'package:flutterapp/dendronapp/generatedaccountwidget/generated/GeneratedFirstnameWidget.dart';
import 'package:flutterapp/dendronapp/generatedaccountwidget/generated/GeneratedEmailadressWidget.dart';
import 'package:flutterapp/dendronapp/generatedaccountwidget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/dendronapp/generatedaccountwidget/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dendronapp/generatedaccountwidget/generated/GeneratedRectangle12Widget.dart';

/* Frame Account 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAccountWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 175, 56),
                ),
              ),
              Positioned(
                left: 37.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 44.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 44.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8026666666666666;

                  final double height =
                      constraints.maxHeight * 0.06596701649175413;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.09866666666666667,
                        y: constraints.maxHeight * 0.5787106446776612,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle10Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 70.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 24.0,
                child: GeneratedFirstnameWidget(),
              ),
              Positioned(
                left: 66.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 24.0,
                child: GeneratedLastnameWidget(),
              ),
              Positioned(
                left: 66.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 24.0,
                child: GeneratedEmailadressWidget(),
              ),
              Positioned(
                left: 103.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 43.0,
                child: GeneratedRectangle9Widget5(),
              ),
              Positioned(
                left: 146.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 40.0,
                child: GeneratedSubmitWidget(),
              ),
              Positioned(
                left: 138.0,
                top: 156.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 72.0,
                child: GeneratedCodiconaccountWidget(),
              )
            ]),
      ),
    ));
  }
}
