import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget/generated/GeneratedRectangle9Widget24.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget/generated/GeneratedRectangle10Widget10.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget/generated/GeneratedDeleteWidget1.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget/generated/GeneratedRectangle4Widget4.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget/generated/GeneratedDendronWidget8.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget/generated/GeneratedRectangle7Widget9.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget/generated/GeneratedVectorWidget44.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget/generated/GeneratedAddWidget3.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget/generated/GeneratedRectangle6Widget4.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget/generated/GeneratedFrame4Widget.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget/generated/GeneratedRectangle5Widget4.dart';

/* Frame 1st page 
    Autogenerated by FlutLab FTF Generator
  */
class Generated1stpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.horizontal,
          child: Container(
              width: 375.0,
              child: Stack(children: [
                Container(
                    height: constraints.maxHeight,
                    child: Container(
                      width: 375.0,
                      height: 667.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 232, 175, 56),
                              ),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 10.0,
                              right: null,
                              bottom: null,
                              width: 150.0,
                              height: 49.0,
                              child: GeneratedDendronWidget8(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.0799218241373698;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        29.970684051513672;

                                double percentHeight = 0.044977740011830025;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        30.000152587890625;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.8506666666666667,
                                      translateY: constraints.maxHeight *
                                          0.03298350824587706,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget44())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 80.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 46.489410400390625,
                              child: GeneratedGroup8Widget(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 154.0,
                              right: null,
                              bottom: null,
                              width: 124.0,
                              height: 49.0,
                              child: GeneratedRectangle3Widget(),
                            ),
                            Positioned(
                              left: 207.0,
                              top: 153.0,
                              right: null,
                              bottom: null,
                              width: 124.0,
                              height: 49.0,
                              child: GeneratedRectangle5Widget4(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 229.0,
                              right: null,
                              bottom: null,
                              width: 124.0,
                              height: 49.0,
                              child: GeneratedRectangle4Widget4(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 229.0,
                              right: null,
                              bottom: null,
                              width: 124.0,
                              height: 49.0,
                              child: GeneratedRectangle6Widget4(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 304.0,
                              right: null,
                              bottom: null,
                              width: 124.0,
                              height: 49.0,
                              child: GeneratedRectangle7Widget9(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 303.0,
                              right: null,
                              bottom: null,
                              width: 124.0,
                              height: 49.0,
                              child: GeneratedRectangle8Widget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 478.0,
                              right: null,
                              bottom: null,
                              width: 135.0,
                              height: 53.0,
                              child: GeneratedRectangle9Widget24(),
                            ),
                            Positioned(
                              left: 192.0,
                              top: 478.0,
                              right: null,
                              bottom: null,
                              width: 135.0,
                              height: 53.0,
                              child: GeneratedRectangle10Widget10(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 579.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 49.0,
                              child: GeneratedFrame4Widget(),
                            ),
                            Positioned(
                              left: 94.0,
                              top: 483.0,
                              right: null,
                              bottom: null,
                              width: 138.5078582763672,
                              height: 51.489410400390625,
                              child: GeneratedAddWidget3(),
                            ),
                            Positioned(
                              left: 210.0,
                              top: 483.0,
                              right: null,
                              bottom: null,
                              width: 135.5078582763672,
                              height: 48.489410400390625,
                              child: GeneratedDeleteWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
