import 'package:flutter/material.dart';
import 'package:flutterapp/dendronapp/generateddecicionsettingswidget/generated/GeneratedEditWidget.dart';
import 'package:flutterapp/dendronapp/generateddecicionsettingswidget/generated/GeneratedReviewWidget.dart';
import 'package:flutterapp/dendronapp/generateddecicionsettingswidget/generated/GeneratedVectorWidget34.dart';
import 'package:flutterapp/dendronapp/generateddecicionsettingswidget/generated/GeneratedRectangle18Widget6.dart';
import 'package:flutterapp/dendronapp/generateddecicionsettingswidget/generated/GeneratedRectangle16Widget1.dart';
import 'package:flutterapp/dendronapp/generateddecicionsettingswidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/dendronapp/generateddecicionsettingswidget/generated/GeneratedDeleteWidget.dart';
import 'package:flutterapp/dendronapp/generateddecicionsettingswidget/generated/GeneratedArchiveWidget1.dart';
import 'package:flutterapp/dendronapp/generateddecicionsettingswidget/generated/GeneratedVectorWidget35.dart';
import 'package:flutterapp/dendronapp/generateddecicionsettingswidget/generated/GeneratedRectangle15Widget10.dart';
import 'package:flutterapp/dendronapp/generateddecicionsettingswidget/generated/GeneratedVectorWidget33.dart';
import 'package:flutterapp/dendronapp/generateddecicionsettingswidget/generated/GeneratedXWidget17.dart';
import 'package:flutterapp/dendronapp/generateddecicionsettingswidget/generated/GeneratedCarbonviewWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dendronapp/generateddecicionsettingswidget/generated/GeneratedVectorWidget38.dart';
import 'package:flutterapp/dendronapp/generateddecicionsettingswidget/generated/GeneratedDoneWidget5.dart';
import 'package:flutterapp/dendronapp/generateddecicionsettingswidget/generated/GeneratedRectangle17Widget6.dart';

/* Frame decicion settings
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDecicionsettingsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 337.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(30.0),
          topRight: Radius.circular(30.0),
          bottomRight: Radius.circular(0.0),
          bottomLeft: Radius.circular(0.0),
        ),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.only(
                topLeft: Radius.circular(30.0),
                topRight: Radius.circular(30.0),
                bottomRight: Radius.circular(0.0),
                bottomLeft: Radius.circular(0.0),
              ),
              child: Container(
                color: Color.fromARGB(255, 156, 107, 6),
              ),
            ),
            Positioned(
              left: 338.0,
              top: 12.0,
              right: null,
              bottom: null,
              width: 23.0,
              height: 38.0,
              child: GeneratedXWidget17(),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 224.0,
              height: 43.0,
              child: TransformHelper.translate(
                  x: -8.50,
                  y: -114.00,
                  z: 0,
                  child: GeneratedRectangle14Widget()),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 224.00001525878906,
              height: 43.0,
              child: TransformHelper.translate(
                  x: -8.50,
                  y: -56.00,
                  z: 0,
                  child: GeneratedRectangle15Widget10()),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 224.0,
              height: 43.0,
              child: TransformHelper.translate(
                  x: -8.50,
                  y: -1.00,
                  z: 0,
                  child: GeneratedRectangle16Widget1()),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 224.0,
              height: 43.0,
              child: TransformHelper.translate(
                  x: -10.50,
                  y: 59.00,
                  z: 0,
                  child: GeneratedRectangle17Widget6()),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 224.0,
              height: 43.0,
              child: TransformHelper.translate(
                  x: -9.50,
                  y: 120.00,
                  z: 0,
                  child: GeneratedRectangle18Widget6()),
            ),
            Positioned(
              left: 147.0,
              top: 36.0,
              right: null,
              bottom: null,
              width: 165.0,
              height: 43.0,
              child: GeneratedEditWidget(),
            ),
            Positioned(
              left: 140.0,
              top: 94.0,
              right: null,
              bottom: null,
              width: 168.0,
              height: 46.0,
              child: GeneratedDoneWidget5(),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 165.0,
              height: 43.0,
              child: TransformHelper.translate(
                  x: 13.00, y: 61.00, z: 0, child: GeneratedDeleteWidget()),
            ),
            Positioned(
              left: 115.0,
              top: 269.0,
              right: null,
              bottom: null,
              width: 165.0,
              height: 43.0,
              child: GeneratedArchiveWidget1(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.064;
                double scaleX = (constraints.maxWidth * percentWidth) / 24.0;

                double percentHeight = 0.0648139251799541;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 21.84229278564453;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.616,
                      translateY: constraints.maxHeight * 0.13329717030511057,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget33())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.05333333333333334;
                double scaleX = (constraints.maxWidth * percentWidth) / 20.0;

                double percentHeight = 0.055975713078982754;
                double scaleY = (constraints.maxHeight * percentHeight) /
                    18.863815307617188;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.632,
                      translateY: constraints.maxHeight * 0.8256278108772255,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget34())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.05333333333333334;
                double scaleX = (constraints.maxWidth * percentWidth) / 20.0;

                double percentHeight = 0.05892179132569084;
                double scaleY = (constraints.maxHeight * percentHeight) /
                    19.856643676757812;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.6266666666666667,
                      translateY: constraints.maxHeight * 0.6459164039317508,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget35())
                ]);
              }),
            ),
            Positioned(
              left: 233.0,
              top: 157.0,
              right: null,
              bottom: null,
              width: 25.0,
              height: 25.0,
              child: GeneratedCarbonviewWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.05333333333333334;
                double scaleX = (constraints.maxWidth * percentWidth) / 20.0;

                double percentHeight = 0.05892176868653792;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 19.85663604736328;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.624,
                      translateY: constraints.maxHeight * 0.3159545988994112,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget38())
                ]);
              }),
            ),
            Positioned(
              left: 115.0,
              top: 150.0,
              right: null,
              bottom: null,
              width: 165.0,
              height: 43.0,
              child: GeneratedReviewWidget(),
            )
          ]),
    ));
  }
}
