import 'package:flutter/material.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget6/generated/GeneratedFrame4Widget6.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget6/generated/GeneratedGroup8Widget6.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget6/generated/GeneratedRectangle3Widget14.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget6/generated/GeneratedVectorWidget50.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget6/generated/GeneratedRectangle7Widget20.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget6/generated/GeneratedRectangle9Widget36.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget6/generated/GeneratedRectangle6Widget16.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget6/generated/GeneratedRectangle11Widget2.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget6/generated/GeneratedDendronWidget14.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget6/generated/GeneratedRectangle4Widget16.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget6/generated/GeneratedRectangle8Widget12.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget6/generated/GeneratedDeleteWidget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget6/generated/GeneratedRectangle10Widget16.dart';
import 'package:flutterapp/dendronapp/generated1stpagewidget6/generated/GeneratedAddWidget9.dart';

/* Frame 1st page 
    Autogenerated by FlutLab FTF Generator
  */
class Generated1stpageWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 175, 56),
                ),
              ),
              Positioned(
                left: 123.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 49.0,
                child: GeneratedDendronWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.0799218241373698;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      29.970684051513672;

                  double percentHeight = 0.044977740011830025;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      30.000152587890625;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8506666666666667,
                        translateY: constraints.maxHeight * 0.03298350824587706,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget50())
                  ]);
                }),
              ),
              Positioned(
                left: 37.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 46.489410400390625,
                child: GeneratedGroup8Widget6(),
              ),
              Positioned(
                left: 46.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child: GeneratedRectangle4Widget16(),
              ),
              Positioned(
                left: 208.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child: GeneratedRectangle6Widget16(),
              ),
              Positioned(
                left: 208.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child: GeneratedRectangle11Widget2(),
              ),
              Positioned(
                left: 47.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child: GeneratedRectangle7Widget20(),
              ),
              Positioned(
                left: 208.0,
                top: 303.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child: GeneratedRectangle8Widget12(),
              ),
              Positioned(
                left: 40.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 49.0,
                child: GeneratedFrame4Widget6(),
              ),
              Positioned(
                left: 43.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child: GeneratedRectangle3Widget14(),
              ),
              Positioned(
                left: 60.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 53.0,
                child: GeneratedRectangle9Widget36(),
              ),
              Positioned(
                left: 192.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 53.0,
                child: GeneratedRectangle10Widget16(),
              ),
              Positioned(
                left: 94.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 138.5078582763672,
                height: 51.489410400390625,
                child: GeneratedAddWidget9(),
              ),
              Positioned(
                left: 210.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 135.5078582763672,
                height: 48.489410400390625,
                child: GeneratedDeleteWidget7(),
              )
            ]),
      ),
    ));
  }
}
