import 'package:flutter/material.dart';

/* Frame carbon:view
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCarbonviewWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 32.0,
        height: 32.0,
      ),
    ));
  }
}
