import 'package:flutter/material.dart';
import 'package:flutterapp/dendronapp/generatedswipeleftwidget/generated/GeneratedFiltreWidget.dart';
import 'package:flutterapp/dendronapp/generatedswipeleftwidget/generated/GeneratedVectorWidget3.dart';
import 'package:flutterapp/dendronapp/generatedswipeleftwidget/generated/GeneratedVectorWidget.dart';
import 'package:flutterapp/dendronapp/generatedswipeleftwidget/generated/GeneratedVectorWidget1.dart';
import 'package:flutterapp/dendronapp/generatedswipeleftwidget/generated/GeneratedFrame27Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dendronapp/generatedswipeleftwidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/dendronapp/generatedswipeleftwidget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/dendronapp/generatedswipeleftwidget/generated/GeneratedVectorWidget2.dart';
import 'package:flutterapp/dendronapp/generatedswipeleftwidget/generated/GeneratedDendronWidget.dart';

/* Frame swipe left 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSwipeleftWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedHomescreenWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
          return SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: Container(
                width: 375.0,
                child: Stack(children: [
                  Container(
                      height: constraints.maxHeight,
                      child: Container(
                        width: 375.0,
                        height: 667.0,
                        child: Stack(
                            fit: StackFit.expand,
                            alignment: Alignment.center,
                            overflow: Overflow.visible,
                            children: [
                              ClipRRect(
                                borderRadius: BorderRadius.zero,
                                child: Container(
                                  color: Color.fromARGB(255, 232, 175, 56),
                                ),
                              ),
                              Positioned(
                                left: 125.0,
                                top: 6.0,
                                right: null,
                                bottom: null,
                                width: 150.0,
                                height: 49.0,
                                child: GeneratedDendronWidget(),
                              ),
                              Positioned(
                                left: null,
                                top: null,
                                right: null,
                                bottom: null,
                                width: 191.0,
                                height: 43.0,
                                child: TransformHelper.translate(
                                    x: 12.00,
                                    y: 208.00,
                                    z: 0,
                                    child: GeneratedRectangle9Widget()),
                              ),
                              Positioned(
                                left: null,
                                top: null,
                                right: null,
                                bottom: null,
                                width: 77.0,
                                height: 40.0,
                                child: TransformHelper.translate(
                                    x: 12.00,
                                    y: 209.50,
                                    z: 0,
                                    child: GeneratedFiltreWidget()),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  double percentWidth = 0.041626012166341146;
                                  double scaleX =
                                      (constraints.maxWidth * percentWidth) /
                                          15.60975456237793;

                                  double percentHeight = 0.0239880059970015;
                                  double scaleY =
                                      (constraints.maxHeight * percentHeight) /
                                          16.0;

                                  return Stack(children: [
                                    TransformHelper.translateAndScale(
                                        translateX: constraints.maxWidth *
                                            0.6277073160807292,
                                        translateY: constraints.maxHeight *
                                            0.9460269865067467,
                                        translateZ: 0,
                                        scaleX: scaleX,
                                        scaleY: scaleY,
                                        scaleZ: 1,
                                        child: GeneratedVectorWidget())
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  double percentWidth = 0.04422765096028646;
                                  double scaleX =
                                      (constraints.maxWidth * percentWidth) /
                                          16.585369110107422;

                                  double percentHeight = 0.0239880059970015;
                                  double scaleY =
                                      (constraints.maxHeight * percentHeight) /
                                          16.0;

                                  return Stack(children: [
                                    TransformHelper.translateAndScale(
                                        translateX: constraints.maxWidth *
                                            0.4872197672526042,
                                        translateY: constraints.maxHeight *
                                            0.9460269865067467,
                                        translateZ: 0,
                                        scaleX: scaleX,
                                        scaleY: scaleY,
                                        scaleZ: 1,
                                        child: GeneratedVectorWidget1())
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  double percentWidth = 0.041626012166341146;
                                  double scaleX =
                                      (constraints.maxWidth * percentWidth) /
                                          15.60975456237793;

                                  double percentHeight = 0.0239880059970015;
                                  double scaleY =
                                      (constraints.maxHeight * percentHeight) /
                                          16.0;

                                  return Stack(children: [
                                    TransformHelper.translateAndScale(
                                        translateX: constraints.maxWidth *
                                            0.34933333333333333,
                                        translateY: constraints.maxHeight *
                                            0.9460269865067467,
                                        translateZ: 0,
                                        scaleX: scaleX,
                                        scaleY: scaleY,
                                        scaleZ: 1,
                                        child: GeneratedVectorWidget2())
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  double percentWidth = 0.0799218241373698;
                                  double scaleX =
                                      (constraints.maxWidth * percentWidth) /
                                          29.970684051513672;

                                  double percentHeight = 0.044977740011830025;
                                  double scaleY =
                                      (constraints.maxHeight * percentHeight) /
                                          30.000152587890625;

                                  return Stack(children: [
                                    TransformHelper.translateAndScale(
                                        translateX:
                                            constraints.maxWidth * 0.864,
                                        translateY: constraints.maxHeight *
                                            0.03298350824587706,
                                        translateZ: 0,
                                        scaleX: scaleX,
                                        scaleY: scaleY,
                                        scaleZ: 1,
                                        child: GeneratedVectorWidget3())
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 298.0,
                                top: 570.0,
                                right: null,
                                bottom: null,
                                width: 56.0,
                                height: 56.0,
                                child: GeneratedGroup21Widget(),
                              ),
                              Positioned(
                                left: 13.0,
                                top: 72.0,
                                right: null,
                                bottom: null,
                                width: 353.0,
                                height: 388.0,
                                child: GeneratedFrame27Widget(),
                              )
                            ]),
                      ))
                ])),
          );
        }),
      ),
    ));
  }
}
