import 'package:flutter/material.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedAreabuttonWidget1.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedDateWidget44.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedAreaWidget14.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedDoneWidget7.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedReviewsWidget1.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedReviewsboxWidget.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedGoalsWidget2.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedGobackWidget1.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedDatebuttonWidget1.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedGoalsboxWidget1.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedCriteriaWidget2.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedReviewWidget2.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedGoalstitleWidget1.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedCriteriatitleWidget1.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedDonebuttonWidget1.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedReviewbuttonWidget1.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedDecisiontitleWidget1.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedReviewstitleWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dendronapp/generateddecisionlog2widget/generated/GeneratedCriteriaWidget3.dart';

/* Frame decision log  2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDecisionlog2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 365.0,
              height: 667.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 232, 175, 56),
                      ),
                    ),
                    Positioned(
                      left: 30.0,
                      top: 49.0,
                      right: null,
                      bottom: null,
                      width: 315.0,
                      height: 48.0,
                      child: GeneratedDecisiontitleWidget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.05333332950121736;
                        double scaleX = (constraints.maxWidth * percentWidth) /
                            19.466665267944336;

                        double percentHeight = 0.022488755622188907;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) / 15.0;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.07200000188122056,
                              translateY:
                                  constraints.maxHeight * 0.044977511244377814,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedGobackWidget1())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 183.0,
                      top: 108.0,
                      right: null,
                      bottom: null,
                      width: 157.0,
                      height: 36.0,
                      child: GeneratedDatebuttonWidget1(),
                    ),
                    Positioned(
                      left: 25.0,
                      top: 303.0,
                      right: null,
                      bottom: null,
                      width: 157.0,
                      height: 36.0,
                      child: GeneratedDonebuttonWidget1(),
                    ),
                    Positioned(
                      left: 185.0,
                      top: 303.0,
                      right: null,
                      bottom: null,
                      width: 157.0,
                      height: 36.0,
                      child: GeneratedReviewbuttonWidget1(),
                    ),
                    Positioned(
                      left: 25.0,
                      top: 108.0,
                      right: null,
                      bottom: null,
                      width: 157.0,
                      height: 36.0,
                      child: GeneratedAreabuttonWidget1(),
                    ),
                    Positioned(
                      left: 71.0,
                      top: 109.0,
                      right: null,
                      bottom: null,
                      width: 90.0,
                      height: 57.0,
                      child: GeneratedAreaWidget14(),
                    ),
                    Positioned(
                      left: 226.0,
                      top: 109.0,
                      right: null,
                      bottom: null,
                      width: 159.0,
                      height: 34.0,
                      child: GeneratedDateWidget44(),
                    ),
                    Positioned(
                      left: 72.0,
                      top: 303.0,
                      right: null,
                      bottom: null,
                      width: 159.0,
                      height: 34.0,
                      child: GeneratedDoneWidget7(),
                    ),
                    Positioned(
                      left: 221.0,
                      top: 304.0,
                      right: null,
                      bottom: null,
                      width: 159.0,
                      height: 34.0,
                      child: GeneratedReviewWidget2(),
                    ),
                    Positioned(
                      left: 27.0,
                      top: 150.0,
                      right: null,
                      bottom: null,
                      width: 315.0,
                      height: 41.0,
                      child: GeneratedGoalstitleWidget1(),
                    ),
                    Positioned(
                      left: 22.0,
                      top: 344.0,
                      right: null,
                      bottom: null,
                      width: 315.0,
                      height: 44.0,
                      child: GeneratedCriteriatitleWidget1(),
                    ),
                    Positioned(
                      left: 22.0,
                      top: 507.0,
                      right: null,
                      bottom: null,
                      width: 315.0,
                      height: 44.0,
                      child: GeneratedReviewstitleWidget(),
                    ),
                    Positioned(
                      left: 136.0,
                      top: 153.0,
                      right: null,
                      bottom: null,
                      width: 158.8372039794922,
                      height: 51.978721618652344,
                      child: GeneratedGoalsWidget2(),
                    ),
                    Positioned(
                      left: 118.0,
                      top: 347.0,
                      right: null,
                      bottom: null,
                      width: 158.8372039794922,
                      height: 51.978721618652344,
                      child: GeneratedCriteriaWidget2(),
                    ),
                    Positioned(
                      left: 117.0,
                      top: 510.0,
                      right: null,
                      bottom: null,
                      width: 158.8372039794922,
                      height: 51.978721618652344,
                      child: GeneratedReviewsWidget1(),
                    )
                  ]),
            ),
            Positioned(
              left: 25.0,
              top: 196.0,
              right: null,
              bottom: null,
              width: 315.0,
              height: 103.0,
              child: GeneratedGoalsboxWidget1(),
            ),
            Positioned(
              left: 19.0,
              top: 400.0,
              right: null,
              bottom: null,
              width: 315.0,
              height: 103.0,
              child: GeneratedCriteriaWidget3(),
            ),
            Positioned(
              left: 23.0,
              top: 557.0,
              right: null,
              bottom: null,
              width: 315.0,
              height: 103.0,
              child: GeneratedReviewsboxWidget(),
            )
          ]),
    ));
  }
}
