import 'package:flutter/material.dart';
import 'package:flutterapp/dendronapp/generatedareasectionwidget/generated/GeneratedKeyboardWidget.dart';
import 'package:flutterapp/dendronapp/generatedareasectionwidget/generated/GeneratedXWidget.dart';
import 'package:flutterapp/dendronapp/generatedareasectionwidget/generated/GeneratedFrame29Widget.dart';

/* Frame Area Section   
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAreaSectionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 370.0,
        height: 360.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 232, 175, 56),
                ),
              ),
              Positioned(
                left: 328.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 38.0,
                child: GeneratedXWidget(),
              ),
              Positioned(
                left: 106.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 69.0,
                child: GeneratedFrame29Widget(),
              ),
              Positioned(
                left: 5.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 217.0,
                child: GeneratedKeyboardWidget(),
              )
            ]),
      ),
    ));
  }
}
