import 'package:flutter/material.dart';
import 'package:flutterapp/dendronapp/generatedhomescreenwidget/generated/GeneratedFrame21Widget.dart';
import 'package:flutterapp/dendronapp/generatedhomescreenwidget/generated/GeneratedVectorWidget8.dart';
import 'package:flutterapp/dendronapp/generatedhomescreenwidget/generated/GeneratedVectorWidget9.dart';
import 'package:flutterapp/dendronapp/generatedhomescreenwidget/generated/GeneratedFrame22Widget1.dart';
import 'package:flutterapp/dendronapp/generatedhomescreenwidget/generated/GeneratedVectorWidget10.dart';
import 'package:flutterapp/dendronapp/generatedhomescreenwidget/generated/GeneratedVectorWidget12.dart';
import 'package:flutterapp/dendronapp/generatedhomescreenwidget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/dendronapp/generatedhomescreenwidget/generated/GeneratedRemindersWidget.dart';
import 'package:flutterapp/dendronapp/generatedhomescreenwidget/generated/GeneratedLearningsWidget.dart';
import 'package:flutterapp/dendronapp/generatedhomescreenwidget/generated/GeneratedDendronWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame home screen 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomescreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedSwiperightWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                return SingleChildScrollView(
                  scrollDirection: Axis.horizontal,
                  child: Container(
                      width: 375.0,
                      child: Stack(children: [
                        Container(
                            height: constraints.maxHeight,
                            child: Container(
                              width: 375.0,
                              height: 667.0,
                              child: Stack(
                                  fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  overflow: Overflow.visible,
                                  children: [
                                    ClipRRect(
                                      borderRadius: BorderRadius.zero,
                                      child: Container(
                                        color:
                                            Color.fromARGB(255, 232, 175, 56),
                                      ),
                                    ),
                                    Positioned(
                                      left: 123.0,
                                      top: 8.0,
                                      right: null,
                                      bottom: null,
                                      width: 150.0,
                                      height: 49.0,
                                      child: GeneratedDendronWidget1(),
                                    ),
                                    Positioned(
                                      left: 117.0,
                                      top: 80.0,
                                      right: null,
                                      bottom: null,
                                      width: 170.0,
                                      height: 55.0,
                                      child: GeneratedLearningsWidget(),
                                    ),
                                    Positioned(
                                      left: 111.0,
                                      top: 325.0,
                                      right: null,
                                      bottom: null,
                                      width: 154.0,
                                      height: 42.0,
                                      child: GeneratedRemindersWidget(),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 0.0,
                                      right: 0.0,
                                      bottom: 0.0,
                                      width: null,
                                      height: null,
                                      child: LayoutBuilder(builder:
                                          (BuildContext context,
                                              BoxConstraints constraints) {
                                        double percentWidth =
                                            0.042477877298990885;
                                        double scaleX = (constraints.maxWidth *
                                                percentWidth) /
                                            15.929203987121582;

                                        double percentHeight =
                                            0.0239880059970015;
                                        double scaleY = (constraints.maxHeight *
                                                percentHeight) /
                                            16.0;

                                        return Stack(children: [
                                          TransformHelper.translateAndScale(
                                              translateX: constraints.maxWidth *
                                                  0.6321888020833333,
                                              translateY:
                                                  constraints.maxHeight *
                                                      0.9475262368815592,
                                              translateZ: 0,
                                              scaleX: scaleX,
                                              scaleY: scaleY,
                                              scaleZ: 1,
                                              child: GeneratedVectorWidget8())
                                        ]);
                                      }),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 0.0,
                                      right: 0.0,
                                      bottom: 0.0,
                                      width: null,
                                      height: null,
                                      child: LayoutBuilder(builder:
                                          (BuildContext context,
                                              BoxConstraints constraints) {
                                        double percentWidth =
                                            0.042477877298990885;
                                        double scaleX = (constraints.maxWidth *
                                                percentWidth) /
                                            15.929203987121582;

                                        double percentHeight =
                                            0.0239880059970015;
                                        double scaleY = (constraints.maxHeight *
                                                percentHeight) /
                                            16.0;

                                        return Stack(children: [
                                          TransformHelper.translateAndScale(
                                              translateX: constraints.maxWidth *
                                                  0.4877639973958333,
                                              translateY:
                                                  constraints.maxHeight *
                                                      0.9475262368815592,
                                              translateZ: 0,
                                              scaleX: scaleX,
                                              scaleY: scaleY,
                                              scaleZ: 1,
                                              child: GeneratedVectorWidget9())
                                        ]);
                                      }),
                                    ),
                                    Positioned(
                                      left: 133.0,
                                      top: 632.0,
                                      right: null,
                                      bottom: null,
                                      width: 15.929203987121582,
                                      height: 16.0,
                                      child: GeneratedVectorWidget10(),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 0.0,
                                      right: 0.0,
                                      bottom: 0.0,
                                      width: null,
                                      height: null,
                                      child: LayoutBuilder(builder:
                                          (BuildContext context,
                                              BoxConstraints constraints) {
                                        double percentWidth =
                                            0.0799218241373698;
                                        double scaleX = (constraints.maxWidth *
                                                percentWidth) /
                                            29.970684051513672;

                                        double percentHeight =
                                            0.044977740011830025;
                                        double scaleY = (constraints.maxHeight *
                                                percentHeight) /
                                            30.000152587890625;

                                        return Stack(children: [
                                          TransformHelper.translateAndScale(
                                              translateX:
                                                  constraints.maxWidth * 0.872,
                                              translateY:
                                                  constraints.maxHeight *
                                                      0.029985007496251874,
                                              translateZ: 0,
                                              scaleX: scaleX,
                                              scaleY: scaleY,
                                              scaleZ: 1,
                                              child: GeneratedVectorWidget12())
                                        ]);
                                      }),
                                    ),
                                    Positioned(
                                      left: 298.0,
                                      top: 574.0,
                                      right: null,
                                      bottom: null,
                                      width: 56.0,
                                      height: 56.0,
                                      child: GeneratedGroup20Widget(),
                                    )
                                  ]),
                            ))
                      ])),
                );
              }),
              Positioned(
                left: 33.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 177.0,
                child: GeneratedFrame21Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 384.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 156.0,
                child: GeneratedFrame22Widget1(),
              )
            ]),
      ),
    ));
  }
}
