import 'package:flutter/material.dart';
import 'package:flutterapp/dendronapp/generatedswiperightwidget/generated/GeneratedDendronWidget2.dart';
import 'package:flutterapp/dendronapp/generatedswiperightwidget/generated/GeneratedVectorWidget19.dart';
import 'package:flutterapp/dendronapp/generatedswiperightwidget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/dendronapp/generatedswiperightwidget/generated/GeneratedVectorWidget26.dart';
import 'package:flutterapp/dendronapp/generatedswiperightwidget/generated/GeneratedVectorWidget23.dart';
import 'package:flutterapp/dendronapp/generatedswiperightwidget/generated/GeneratedVectorWidget24.dart';
import 'package:flutterapp/dendronapp/generatedswiperightwidget/generated/GeneratedVectorWidget25.dart';
import 'package:flutterapp/dendronapp/generatedswiperightwidget/generated/GeneratedFrame23Widget.dart';
import 'package:flutterapp/dendronapp/generatedswiperightwidget/generated/GeneratedProgressionWidget.dart';
import 'package:flutterapp/dendronapp/generatedswiperightwidget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/dendronapp/generatedswiperightwidget/generated/GeneratedArchiveWidget.dart';
import 'package:flutterapp/dendronapp/generatedswiperightwidget/generated/GeneratedRectangle18Widget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Swipe right 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSwiperightWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedHomescreenWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 667.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 232, 175, 56),
                  ),
                ),
                Positioned(
                  left: 115.0,
                  top: 7.0,
                  right: null,
                  bottom: null,
                  width: 150.0,
                  height: 49.0,
                  child: GeneratedDendronWidget2(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.0799218241373698;
                    double scaleX = (constraints.maxWidth * percentWidth) /
                        29.970684051513672;

                    double percentHeight = 0.044977740011830025;
                    double scaleY = (constraints.maxHeight * percentHeight) /
                        30.000152587890625;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.8693333333333333,
                          translateY:
                              constraints.maxHeight * 0.02848575712143928,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget19())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.3200000203450521;

                    final double height =
                        constraints.maxHeight * 0.0239880059970015;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.328,
                          y: constraints.maxHeight * 0.9460269865067467,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroup18Widget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 260.0,
                  height: 43.0,
                  child: TransformHelper.translate(
                      x: 6.50,
                      y: -35.00,
                      z: 0,
                      child: GeneratedRectangle16Widget()),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: null,
                  width: 260.0,
                  height: 43.0,
                  child: TransformHelper.translate(
                      x: 8.50,
                      y: -101.00,
                      z: 0,
                      child: GeneratedRectangle18Widget5()),
                ),
                Positioned(
                  left: 129.0,
                  top: 213.0,
                  right: null,
                  bottom: null,
                  width: 168.0,
                  height: 46.0,
                  child: GeneratedArchiveWidget(),
                ),
                Positioned(
                  left: 100.0,
                  top: 279.0,
                  right: null,
                  bottom: null,
                  width: 190.0,
                  height: 46.0,
                  child: GeneratedProgressionWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.053333343505859374;
                    double scaleX = (constraints.maxWidth * percentWidth) /
                        20.000003814697266;

                    double percentHeight = 0.028485759981032432;
                    double scaleY = (constraints.maxHeight * percentHeight) /
                        19.000001907348633;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.7253333333333334,
                          translateY:
                              constraints.maxHeight * 0.3373313343328336,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget23())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.048;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 18.0;

                    double percentHeight = 0.026986506746626688;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 18.0;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.7333333333333333,
                          translateY:
                              constraints.maxHeight * 0.43478260869565216,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget24())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.037333333333333336;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 14.0;

                    double percentHeight = 0.008995502248875561;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 6.0;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.744,
                          translateY:
                              constraints.maxHeight * 0.44227886056971516,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget25())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.008;
                    double scaleX = (constraints.maxWidth * percentWidth) / 3.0;

                    double percentHeight = 0.004497751124437781;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 3.0;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.7733333333333333,
                          translateY:
                              constraints.maxHeight * 0.44227886056971516,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget26())
                    ]);
                  }),
                ),
                Positioned(
                  left: 64.0,
                  top: 334.0,
                  right: null,
                  bottom: null,
                  width: 260.0,
                  height: 41.0,
                  child: GeneratedFrame23Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
