import 'package:flutter/material.dart';
import 'package:flutterapp/dendronapp/generatedsettingswidget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/dendronapp/generatedsettingswidget/generated/GeneratedAboutWidget.dart';
import 'package:flutterapp/dendronapp/generatedsettingswidget/generated/GeneratedHelpandsupportWidget.dart';
import 'package:flutterapp/dendronapp/generatedsettingswidget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/dendronapp/generatedsettingswidget/generated/GeneratedDendronWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dendronapp/generatedsettingswidget/generated/GeneratedAccountWidget1.dart';
import 'package:flutterapp/dendronapp/generatedsettingswidget/generated/GeneratedBxsupportWidget.dart';
import 'package:flutterapp/dendronapp/generatedsettingswidget/generated/GeneratedCodiconaccountWidget1.dart';
import 'package:flutterapp/dendronapp/generatedsettingswidget/generated/GeneratedVectorWidget30.dart';
import 'package:flutterapp/dendronapp/generatedsettingswidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/dendronapp/generatedsettingswidget/generated/GeneratedVectorWidget29.dart';
import 'package:flutterapp/dendronapp/generatedsettingswidget/generated/GeneratedVectorWidget32.dart';

/* Frame settings 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSettingsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 175, 56),
                ),
              ),
              Positioned(
                left: 124.0,
                top: 2.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 49.0,
                child: GeneratedDendronWidget3(),
              ),
              Positioned(
                left: 33.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedBxsupportWidget(),
              ),
              Positioned(
                left: 65.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 45.0,
                child: GeneratedAccountWidget1(),
              ),
              Positioned(
                left: 65.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 45.0,
                child: GeneratedAboutWidget(),
              ),
              Positioned(
                left: 65.0,
                top: 165.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 45.0,
                child: GeneratedHelpandsupportWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 1.0,
                child: GeneratedLine4Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 297.0016784667969,
                height: 1.0,
                child: GeneratedLine5Widget(),
              ),
              Positioned(
                left: 45.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 295.001708984375,
                height: 1.0,
                child: GeneratedLine6Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.029333333333333333;
                  double scaleX = (constraints.maxWidth * percentWidth) / 11.0;

                  double percentHeight = 0.022488755622188907;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 15.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.10666666666666667,
                        translateY: constraints.maxHeight * 0.3658170914542729,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget29())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06666666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 25.0;

                  double percentHeight = 0.037481259370314844;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.088,
                        translateY: constraints.maxHeight * 0.3583208395802099,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget30())
                  ]);
                }),
              ),
              Positioned(
                left: 33.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedCodiconaccountWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.05333333333333334;
                  double scaleX = (constraints.maxWidth * percentWidth) / 20.0;

                  double percentHeight = 0.022488755622188907;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 15.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.072,
                        translateY:
                            constraints.maxHeight * 0.034482758620689655,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget32())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
