import 'package:flutter/material.dart';
import 'package:flutterapp/dendronapp/generatedarchivelistwidget/generated/GeneratedProgressionbuttonWidget.dart';
import 'package:flutterapp/dendronapp/generatedarchivelistwidget/generated/GeneratedCalanderbuttonWidget1.dart';
import 'package:flutterapp/dendronapp/generatedarchivelistwidget/generated/GeneratedXWidget20.dart';
import 'package:flutterapp/dendronapp/generatedarchivelistwidget/generated/GeneratedScrolllistarchiveWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dendronapp/generatedarchivelistwidget/generated/GeneratedArchivebuttonWidget1.dart';
import 'package:flutterapp/dendronapp/generatedarchivelistwidget/generated/GeneratedFramesectionofarchiveWidget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;

/* Frame Archive list 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedArchivelistWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
          return SingleChildScrollView(
            scrollDirection: Axis.vertical,
            child: Container(
                height: 667.0,
                child: Stack(children: [
                  Container(
                      width: constraints.maxWidth,
                      child: Container(
                        width: 375.0,
                        height: 667.0,
                        child: Stack(
                            fit: StackFit.expand,
                            alignment: Alignment.center,
                            overflow: Overflow.visible,
                            children: [
                              ClipRRect(
                                borderRadius: BorderRadius.zero,
                                child: Container(
                                  color: Color.fromARGB(255, 232, 175, 56),
                                ),
                              ),
                              Positioned(
                                left: 337.0,
                                top: 15.0,
                                right: null,
                                bottom: null,
                                width: 23.0,
                                height: 38.0,
                                child: GeneratedXWidget20(),
                              ),
                              Positioned(
                                left: 78.0,
                                top: 45.0,
                                right: null,
                                bottom: null,
                                width: 200.0,
                                height: 40.0,
                                child: GeneratedArchivebuttonWidget1(),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  final double width =
                                      constraints.maxWidth * 0.94680859375;

                                  final double height = constraints.maxHeight *
                                      0.5864810514664542;

                                  return Stack(children: [
                                    TransformHelper.translate(
                                        x: constraints.maxWidth * 0.04,
                                        y: constraints.maxHeight *
                                            0.14995349615231446,
                                        z: 0,
                                        child: Container(
                                          width: width,
                                          height: height,
                                          child:
                                              GeneratedFramesectionofarchiveWidget(),
                                        ))
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 27.0,
                                top: 93.0,
                                right: null,
                                bottom: null,
                                width: 339.0,
                                height: 377.0,
                                child: GeneratedScrolllistarchiveWidget(),
                              ),
                              Positioned(
                                left: 89.0,
                                top: 590.0,
                                right: null,
                                bottom: null,
                                width: 200.0,
                                height: 35.0,
                                child: GeneratedCalanderbuttonWidget1(),
                              ),
                              Positioned(
                                left: 89.0,
                                top: 526.0,
                                right: null,
                                bottom: null,
                                width: 217.0,
                                height: 46.0,
                                child: GeneratedProgressionbuttonWidget(),
                              )
                            ]),
                      ))
                ])),
          );
        }),
      ),
    ));
  }
}
