import 'package:flutter/material.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget1/generated/GeneratedAddWidget1.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget1/generated/GeneratedDendronWidget6.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget1/generated/GeneratedFrame30Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget1/generated/GeneratedRectangle9Widget20.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget1/generated/GeneratedFrame3Widget3.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget1/generated/GeneratedVectorWidget42.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget1/generated/GeneratedRectangle37Widget.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget1/generated/GeneratedFrame22Widget4.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget1/generated/GeneratedRectangle38Widget1.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget1/generated/GeneratedRectangle36Widget1.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget1/generated/GeneratedFrame3Widget4.dart';

/* Frame 2nd page 
    Autogenerated by FlutLab FTF Generator
  */
class Generated2ndpageWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 175, 56),
                ),
              ),
              Positioned(
                left: 126.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 46.0,
                child: GeneratedDendronWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.0799218241373698;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      29.970684051513672;

                  double percentHeight = 0.044977740011830025;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      30.000152587890625;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.872,
                        translateY: constraints.maxHeight * 0.02848575712143928,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget42())
                  ]);
                }),
              ),
              Positioned(
                left: 36.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 48.0,
                child: GeneratedFrame30Widget(),
              ),
              Positioned(
                left: 338.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 48.0,
                child: GeneratedFrame3Widget3(),
              ),
              Positioned(
                left: 36.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 172.0,
                child: GeneratedFrame22Widget4(),
              ),
              Positioned(
                left: 36.0,
                top: 122.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 398.0,
                child: GeneratedRectangle9Widget20(),
              ),
              Positioned(
                left: 311.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 353.0,
                child: GeneratedRectangle36Widget1(),
              ),
              Positioned(
                left: 307.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 50.0,
                child: GeneratedRectangle37Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 48.0,
                child: GeneratedFrame3Widget4(),
              ),
              Positioned(
                left: 122.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 53.0,
                child: GeneratedRectangle38Widget1(),
              ),
              Positioned(
                left: 155.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 138.5078582763672,
                height: 51.489410400390625,
                child: GeneratedAddWidget1(),
              )
            ]),
      ),
    ));
  }
}
