import 'package:flutter/material.dart';
import 'package:flutterapp/dendronapp/generatedprogressiondetailswidget/generated/GeneratedProgressionWidget2.dart';
import 'package:flutterapp/dendronapp/generatedprogressiondetailswidget/generated/GeneratedXWidget19.dart';
import 'package:flutterapp/dendronapp/generatedprogressiondetailswidget/generated/GeneratedFramesectionofprogressionWidget.dart';
import 'package:flutterapp/dendronapp/generatedprogressiondetailswidget/generated/GeneratedArchivebuttonWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dendronapp/generatedprogressiondetailswidget/generated/GeneratedCalanderbuttonWidget.dart';

/* Frame Progression details 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProgressiondetailsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 175, 56),
                ),
              ),
              Positioned(
                left: 337.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 38.0,
                child: GeneratedXWidget19(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.94680859375;

                  final double height =
                      constraints.maxHeight * 0.5864810972199447;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.02482275390625,
                        y: constraints.maxHeight * 0.22445838848154048,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedProgressionWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 20.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 365.0,
                child: GeneratedFramesectionofprogressionWidget(),
              ),
              Positioned(
                left: 78.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 40.0,
                child: GeneratedArchivebuttonWidget(),
              ),
              Positioned(
                left: 89.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 35.0,
                child: GeneratedCalanderbuttonWidget(),
              )
            ]),
      ),
    ));
  }
}
