import 'package:flutter/material.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget/generated/GeneratedFrame3Widget1.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget/generated/GeneratedAddWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget/generated/GeneratedFrame3Widget2.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget/generated/GeneratedVectorWidget41.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget/generated/GeneratedFrame22Widget3.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget/generated/GeneratedGroup4Widget5.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget/generated/GeneratedRectangle38Widget.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget/generated/GeneratedDendronWidget5.dart';
import 'package:flutterapp/dendronapp/generated2ndpagewidget/generated/GeneratedFrame14Widget.dart';

/* Frame 2nd page 
    Autogenerated by FlutLab FTF Generator
  */
class Generated2ndpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 175, 56),
                ),
              ),
              Positioned(
                left: 126.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 49.0,
                child: GeneratedDendronWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.0799218241373698;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      29.970684051513672;

                  double percentHeight = 0.044977740011830025;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      30.000152587890625;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.872,
                        translateY: constraints.maxHeight * 0.02848575712143928,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget41())
                  ]);
                }),
              ),
              Positioned(
                left: 36.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 48.0,
                child: GeneratedGroup4Widget5(),
              ),
              Positioned(
                left: 338.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 48.0,
                child: GeneratedFrame3Widget1(),
              ),
              Positioned(
                left: 36.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 172.0,
                child: GeneratedFrame22Widget3(),
              ),
              Positioned(
                left: 36.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 48.0,
                child: GeneratedFrame3Widget2(),
              ),
              Positioned(
                left: 122.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 53.0,
                child: GeneratedRectangle38Widget(),
              ),
              Positioned(
                left: 155.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 138.5078582763672,
                height: 51.489410400390625,
                child: GeneratedAddWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.94680859375;

                  final double height =
                      constraints.maxHeight * 0.5864810514664542;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.029333333333333333,
                        y: constraints.maxHeight * 0.20239880059970014,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle13Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 23.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 340.0,
                child: GeneratedFrame14Widget(),
              )
            ]),
      ),
    ));
  }
}
