import 'package:flutter/material.dart';

/* Frame gg:scroll-v
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGgscrollvWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 24.0,
        height: 24.0,
      ),
    ));
  }
}
