import 'package:flutter/material.dart';
import 'package:flutterapp/dendronapp/generatedfiltrewidget9/generated/GeneratedGroup33Widget4.dart';
import 'package:flutterapp/dendronapp/generatedfiltrewidget9/generated/GeneratedGroup26Widget4.dart';
import 'package:flutterapp/dendronapp/generatedfiltrewidget9/generated/GeneratedXWidget14.dart';
import 'package:flutterapp/dendronapp/generatedfiltrewidget9/generated/GeneratedGroup27Widget4.dart';
import 'package:flutterapp/dendronapp/generatedfiltrewidget9/generated/GeneratedGroup4Widget4.dart';
import 'package:flutterapp/dendronapp/generatedfiltrewidget9/generated/GeneratedDoneWidget4.dart';
import 'package:flutterapp/dendronapp/generatedfiltrewidget9/generated/GeneratedGroup30Widget4.dart';
import 'package:flutterapp/dendronapp/generatedfiltrewidget9/generated/GeneratedXWidget15.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dendronapp/generatedfiltrewidget9/generated/GeneratedGroup24Widget4.dart';
import 'package:flutterapp/dendronapp/generatedfiltrewidget9/generated/GeneratedFrame10Widget4.dart';
import 'package:flutterapp/dendronapp/generatedfiltrewidget9/generated/GeneratedFrame6Widget4.dart';
import 'package:flutterapp/dendronapp/generatedfiltrewidget9/generated/GeneratedRectangle15Widget8.dart';

/* Frame filtre 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFiltreWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.only(
        topLeft: Radius.circular(30.0),
        topRight: Radius.circular(30.0),
        bottomRight: Radius.circular(0.0),
        bottomLeft: Radius.circular(0.0),
      ),
      child: Container(
        width: 375.0,
        height: 337.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(30.0),
            topRight: Radius.circular(30.0),
            bottomRight: Radius.circular(0.0),
            bottomLeft: Radius.circular(0.0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(30.0),
                  topRight: Radius.circular(30.0),
                  bottomRight: Radius.circular(0.0),
                  bottomLeft: Radius.circular(0.0),
                ),
                child: Container(
                  color: Color.fromARGB(255, 156, 107, 6),
                ),
              ),
              Positioned(
                left: 412.0,
                top: 7.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 38.0,
                child: GeneratedXWidget14(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 191.0,
                height: 43.0,
                child: TransformHelper.translate(
                    x: -1.00,
                    y: -134.00,
                    z: 0,
                    child: GeneratedGroup30Widget4()),
              ),
              Positioned(
                left: 7.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 52.0,
                child: GeneratedFrame6Widget4(),
              ),
              Positioned(
                left: 10.0,
                top: 163.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 37.000003814697266,
                child: GeneratedGroup4Widget4(),
              ),
              Positioned(
                left: 46.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 40.0,
                child: GeneratedRectangle15Widget8(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 147.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: -30.00, y: 69.50, z: 0, child: GeneratedDoneWidget4()),
              ),
              Positioned(
                left: 186.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 49.0,
                child: GeneratedGroup27Widget4(),
              ),
              Positioned(
                left: 46.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 51.0,
                child: GeneratedGroup26Widget4(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 180.0,
                height: 46.0,
                child: TransformHelper.translate(
                    x: 89.50, y: 64.50, z: 0, child: GeneratedGroup24Widget4()),
              ),
              Positioned(
                left: 329.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 38.0,
                child: GeneratedXWidget15(),
              ),
              Positioned(
                left: 163.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 34.0,
                child: GeneratedGroup33Widget4(),
              ),
              Positioned(
                left: -4.547473508864641e-13,
                top: 97.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 81.0,
                child: GeneratedFrame10Widget4(),
              )
            ]),
      ),
    ));
  }
}
